### PR TITLE
Somewhat finished product

### PR DESCRIPTION
**Pull request by alwin48**
This is somewhat finished.
Need to add Merge functionality.
Will add comments, readme and deploy in next pull request. 

Screenshot (66)

### CODE REVIEW

**Comment by alwin48** [comment]
Also, I couldn't pull this in a new branch.
I only had the option to pull this in master branch

**Comment by anandbaburajan** [comment]
> Also, I couldn't pull this in a new branch.
> I only had the option to pull this in master branch

@alwin48 I'm not sure I got what you mean there, can you tell me more?
Also I see that both #4 and this PR are exactly the same. Is there a reason? Thanks! :)

**Comment by alwin48** [comment]
> > Also, I couldn't pull this in a new branch.
> > I only had the option to pull this in master branch
> 
> @alwin48 I'm not sure I got what you mean there, can you tell me more?
> Also I see that both #4 and this PR are exactly the same. Is there a reason? Thanks! :)

@AnandBaburajan They are not same, please check again. 
When I click create a pull request, they only give option to select from an existing branch.

**Comment by anandbaburajan** [comment]
> They are not same, please check again.

Hmm, right. The screenshot you commented is different. I just checked the files changed in both the PRs, they look the same to me and both show +61 and -30 lines of code too. Am I getting something wrong? Sorry, haha.

> When I click create a pull request, they only give option to select from an existing branch.

Hm, can you also tell me why you created this PR? I thought you were going to continue working at #4 .

> Also, I couldn't pull this in a new branch.

For your future reference, "pull" is usually used to denote "getting stuff from the original repo to a branch in your forked local/remote repo". You can say "I couldn't open a pull request" here instead.

**Comment by alwin48** [comment]
@AnandBaburajan please check this deployed version https://lifetree.netlify.app/

**Comment by alwin48** [comment]
> > They are not same, please check again.
> 
> Hmm, right. The screenshot you commented is different. I just checked the files changed in both the PRs, they look the same to me and both show +61 and -30 lines of code too. Am I getting something wrong? Sorry, haha.

    But they are completely different.
> 
> > When I click create a pull request, they only give option to select from an existing branch.
> 
> Hm, can you also tell me why you created this PR? I thought you were going to continue working at #4 .

I was going to but changed my mind, sorry.
> 
> > Also, I couldn't pull this in a new branch.
> 
> For your future reference, "pull" is usually used to denote "getting stuff from the original repo to a branch in your forked local/remote repo". You can say "I couldn't open a pull request" here instead.

Okay

**Comment by anandbaburajan** [comment]
> @AnandBaburajan please check this deployed version https://lifetree.netlify.app/

Nice!

> But they are completely different.

Then I think something's wrong on my side. Can you please check both https://github.com/FOSS-Cell-GECPKD/Lifetree/pull/4/files and https://github.com/FOSS-Cell-GECPKD/Lifetree/pull/6/files and tell me if you see any differences? I also just checked the commit history, both PRs have the same: `e46c151` and `c0b1645`

**Comment by alwin48** [comment]
> > @AnandBaburajan please check this deployed version https://lifetree.netlify.app/
> 
> Nice!
> 
> > But they are completely different.
> 
> Then I think something's wrong on my side. Can you please check both https://github.com/FOSS-Cell-GECPKD/Lifetree/pull/4/files and https://github.com/FOSS-Cell-GECPKD/Lifetree/pull/6/files and tell me if you see any differences? I also just checked the commit history, both PRs have the same: `e46c151` and `c0b1645`

@AnandBaburajan  Wow, they both are same! I don't know how that happened but this is the code I wrote yesterday night.

**Comment by anandbaburajan** [comment]
> @AnandBaburajan Wow, they both are same! I don't know how that happened but this is the code I wrote yesterday night.

I think maybe you worked on the master branch (#4), then created the new branch for this PR. So both PRs have the same content. So can I go ahead and close the other PR?

**Comment by alwin48** [comment]
> > @AnandBaburajan Wow, they both are same! I don't know how that happened but this is the code I wrote yesterday night.
> 
> I think maybe you worked on the master branch (#4), then created the new branch for this PR. So both PRs have the same content. So can I go ahead and close the other PR?

Yes

**Pull request merged**
